sync: Support switching between snapshot and release tags

diff --git a/build/sync b/build/sync
--- a/build/sync
+++ b/build/sync
@@ -28,23 +28,58 @@ update_feeds() {
 update_src() {
   # Check if the source tree exists
   if [ -d "$SRC" ]; then
-    # Check if we can just update the tree
-    if [ -d "$SRC/.git" ]; then
-      cd_src
-      git pull
-    else
-      # Move the untracked source tree away
+    # Check if we can update the source tree
+    if [ ! -d "$SRC/.git" ]; then
+      # Move any untracked source tree away
       mv "$SRC" "$SRC.old"
     fi
   fi
-  # Clone a fresh copy if the source tree doesn't exist
   if [ ! -d "$SRC" ]; then
+    # Clone a fresh copy if the source tree doesn't exist
     git clone "$GIT" "$SRC"
   fi
+  cd_src
+
+  # Get the current tag, defaulting to main for snapshot builds
+  tag=$(git describe --exact-match --tags 2>/dev/null || echo main)
+
+  # Allow overriding the tag
+  if [ -n "$1" ]; then
+    tag=$1
+    case $tag in
+      snapshot|master)
+        tag="main"
+        ;;
+      release)
+        tag=$(git describe --tags $(git rev-list --tags --max-count=1))
+        ;;
+    esac
+  fi
+
+  # Get the build type (0=snapshot, 1=release)
+  type=1
+  if [ "$tag" == "main" ]; then
+    type=0
+    warn "Checking for updates to OpenWRT snapshot"
+  else
+    warn "Checking for updates to OpenWRT $tag"
+  fi
+
+  # Update the source tree
+  git fetch -t
+  if git checkout "$tag" >/dev/null 2>&1; then
+    if git symbolic-ref HEAD &>/dev/null; then
+      git pull
+    fi
+  else
+    error "Failed to switch to OpenWRT $tag!"
+  fi
+
+  cd_pwd
 }
 sync() {
   # Check for OpenWRT updates
-  update_src
+  update_src "$@"
 
   if [ -z "$ID" ]; then
     error "Must lunch a target to update package feeds!"
